
name: check_build
on: pull_request
runs-on: ubuntu-latest

jobs:
  test:
    - uses: actions/checkout@v2
    - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools setuptools_scm wheel twine
    - name: Build and check
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
